[tox]
envlist =
    codestyle
    py{312,313,314}-test{,-olddeps,-predeps}
    py{312,313,314}-benchmark
isolated_build = true

[testenv]
# Pass through environment variables
passenv =
    HOME
    WINDIR
    CI

# Run tests in temporary directory to avoid importing from source tree
changedir = .tmp/{envname}

description =
    run tests
    olddeps: with the oldest supported version of key dependencies
    predeps: with pre-releases of key dependencies
    benchmark: with performance benchmarks

deps =
    pytest>=8.4.2
    pytest-benchmark[aspect]
    pytest-xdist

    # Oldest dependencies
    olddeps: numpy==2.3.3
    olddeps: astropy==7.2.*
    olddeps: scipy==1.16.1
    olddeps: pandas==2.3.3
    olddeps: tables==3.9.*
    olddeps: GitPython==3.1.44
    olddeps: astroquery==0.4.11
    olddeps: jplephem==2.23
    olddeps: bindensity==0.1.4

pip_pre =
    predeps: true
    !predeps: false

commands =
    pip freeze
    benchmark: pytest --benchmark-only --pyargs rvdata {posargs}
    test: pytest --benchmark-skip -v --pyargs rvdata {posargs}

[testenv:codestyle]
description = check code style with flake8
skip_install = true
changedir = {toxinidir}
deps = flake8-pyproject
commands = flake8 rvdata --count --statistics
