[tox]
envlist =
    py{312,313,314}-test{,-oldestdeps,-devdeps,-predeps}
    py{312,313,314}-benchmark{,-devdeps}
    codestyle
isolated_build = true

[testenv]
# Pass through environment variables
passenv = 
    HOME
    WINDIR
    CI

setenv =
    devdeps: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/astropy/simple https://pypi.anaconda.org/liberfa/simple https://pypi.anaconda.org/scientific-python-nightly-wheels/simple

# Run tests in temporary directory to avoid importing from source tree
changedir = .tmp/{envname}

description =
    run tests
    oldestdeps: with the oldest supported version of key dependencies
    devdeps: with the latest developer version of key dependencies
    predeps: with pre-releases of key dependencies
    benchmark: with performance benchmarks

deps =
    pytest>=7.0
    pytest-benchmark[aspect]
    pytest-xdist
    
    # Oldest dependencies
    oldestdeps: numpy==2.0.*
    oldestdeps: astropy==7.0.*
    oldestdeps: specutils==1.9.*

    # Development dependencies (latest)
    devdeps: numpy>=0.0.dev0
    devdeps: astropy>=0.0.dev0
    devdeps: git+https://github.com/astropy/specutils.git#egg=specutils

install_command =
    !devdeps: python -I -m pip install {opts} {packages}
    devdeps: python -I -m pip install -v --pre {opts} {packages}

pip_pre =
    predeps: true
    !predeps: false

commands =
    pip freeze
    benchmark: pytest \
        --benchmark-only \
        --pyargs rvdata \
        {posargs}
    
    test: pytest \
        --benchmark-skip \
        -v \
        --pyargs rvdata \
        {posargs}

[testenv:codestyle]
description = check code style with flake8
skip_install = true
changedir = {toxinidir}
deps = flake8-pyproject
commands = flake8 rvdata --count --statistics
