name: Continuous Integration and Tests

on:
  push:
    branches:
    - release
    - develop
  pull_request:

jobs:
    codestyle:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Python codestyle check using flake8
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        - name: Install base dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install tox
        - name: Check for runtime errors using flake8
          run: |
            tox -e codestyle

    regression:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run tests
        run: |
          pytest tests/regression