name: Continuous Integration and Tests

on:
  push:
    branches:
    - release
    - develop
  pull_request:

jobs:
    codestyle:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Python codestyle check using flake8
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'
        - name: Install base dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install tox
        - name: Check for runtime errors using flake8
          run: |
            tox -e codestyle

    regression:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
          python-ver: [12, 13]
          tox-env: [test, test-oldestdeps, test-devdeps]
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.${{ matrix.python-ver }} with tox environment ${{ matrix.tox-env }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.${{ matrix.python-ver }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run regression tests with tox
        run: |
          tox -e py3${{ matrix.python-ver }}-${{ matrix.tox-env }}

    benchmark:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest]
          python-ver: [13]
          tox-env: [benchmark, benchmark-devdeps]
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.${{ matrix.python-ver }} with tox environment ${{ matrix.tox-env }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.${{ matrix.python-ver }}'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run benchmark tests with tox
        run: |
          # we're using a temporary file to store the benchmark results, but can't do anything with it until
          # we set up gh-pages to store and display the results.
          tox -e py3${{ matrix.python-ver }}-${{ matrix.tox-env }} -- --benchmark-json ${{ runner.temp }}/output.json

